hab:
  base-location:
    x: -13
    y: 21
    z: 13
  correct-location:
    x: 13
    y: 21
    z: 13

game:
  max-turn-count: 10
  max-player-size: 10
  mode: "NORMAL"
  color-repeat: true
  speed-mode-seconds: 30
